#ifndef CHARACTERDATA_H

#define CHARACTERDATA_H

#include "../Common/Header/D3DUtil.h"
#include "../Common/Header/Struct.h"
#include "../DirectXRendering/Header/Global.h"

using namespace DirectX;


#define CHARACTER_MODEL_NAME "Vampire_A_Lusth"
#define CHARACTER_MODEL_OBJECTPATH ""
#define CHARACTER_MODEL_TEXPATH "Vampire_A_Lusth"
#define CHARACTER_MODEL_EXTENTS XMFLOAT3(0.3f, 1.0f, 0.2f)
#define CHARACTER_MODEL_TYPE Object_Player
#define CHARACTER_MODEL_COLLIDERTYPE Collider_Box
#define CHARACTER_MODEL_MASS 40
#define CHARACTER_MODEL_SCALE XMFLOAT3(10,10,10)
#define CHARACTER_MODEL_RENDERLAYER RenderLayer::Render_Skinned
#define CHARACTER_MODEL_SHADOW true

#define ZOMBIE_MODEL_NAME "Zombie1"
#define ZOMBIE_MODEL_OBJECTPATH "Monster"
#define ZOMBIE_MODEL_TEXPATH "Monster/Zombie1"
#define ZOMBIE_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.2f)
#define ZOMBIE_MODEL_TYPE Object_Monster
#define ZOMBIE_MODEL_COLLIDERTYPE Collider_Box
#define ZOMBIE_MODEL_MASS 40
#define ZOMBIE_MODEL_SCALE XMFLOAT3(12,12,12)
#define ZOMBIE_MODEL_RENDERLAYER RenderLayer::Render_Skinned
#define ZOMBIE_MODEL_SHADOW true

#define HIGHZOMBIE_MODEL_NAME "HighZombie"
#define HIGHZOMBIE_MODEL_OBJECTPATH "Monster"
#define HIGHZOMBIE_MODEL_TEXPATH "Monster/HighZombie"
#define HIGHZOMBIE_MODEL_EXTENTS XMFLOAT3(0.4f, 0.8f, 0.3f)
#define HIGHZOMBIE_MODEL_TYPE Object_Monster
#define HIGHZOMBIE_MODEL_COLLIDERTYPE Collider_Box
#define HIGHZOMBIE_MODEL_MASS 40
#define HIGHZOMBIE_MODEL_SCALE XMFLOAT3(13,13,13)
#define HIGHZOMBIE_MODEL_RENDERLAYER RenderLayer::Render_Skinned
#define HIGHZOMBIE_MODEL_SHADOW true

#define SCAVENGER_MODEL_NAME "scavenger"
#define SCAVENGER_MODEL_OBJECTPATH "Monster"
#define SCAVENGER_MODEL_TEXPATH "Monster/scavenger"
#define SCAVENGER_MODEL_EXTENTS XMFLOAT3(0.25f, 0.8f, 0.3f)
#define SCAVENGER_MODEL_TYPE Object_Monster
#define SCAVENGER_MODEL_COLLIDERTYPE Collider_Box
#define SCAVENGER_MODEL_MASS 40
#define SCAVENGER_MODEL_SCALE XMFLOAT3(9,9,9)
#define SCAVENGER_MODEL_RENDERLAYER RenderLayer::Render_Skinned
#define SCAVENGER_MODEL_SHADOW true

#define CYBER_TWINS_MODEL_NAME "Cyber_Monsters_2"
#define CYBER_TWINS_MODEL_OBJECTPATH "Monster"
#define CYBER_TWINS_MODEL_TEXPATH "Monster/Cyber_Monsters_2"
#define CYBER_TWINS_MODEL_EXTENTS XMFLOAT3(0.4f, 0.8f, 0.3f)
#define CYBER_TWINS_MODEL_TYPE Object_Monster
#define CYBER_TWINS_MODEL_COLLIDERTYPE Collider_Box
#define CYBER_TWINS_MODEL_MASS 40
#define CYBER_TWINS_MODEL_SCALE XMFLOAT3(22,22,22)
#define CYBER_TWINS_MODEL_RENDERLAYER RenderLayer::Render_Skinned
#define CYBER_TWINS_MODEL_SHADOW true

#define GHOUL_MODEL_NAME "Ghoul"
#define GHOUL_MODEL_OBJECTPATH "Monster"
#define GHOUL_MODEL_TEXPATH "Monster/Ghoul"
#define GHOUL_MODEL_EXTENTS XMFLOAT3(0.65f, 1.5f, 0.4f)
#define GHOUL_MODEL_TYPE Object_Monster
#define GHOUL_MODEL_COLLIDERTYPE Collider_Box
#define GHOUL_MODEL_MASS 40
#define GHOUL_MODEL_SCALE XMFLOAT3(13.5f,13.5f,13.5f)
#define GHOUL_MODEL_RENDERLAYER RenderLayer::Render_Skinned
#define GHOUL_MODEL_SHADOW true

#define NECROMANCER_MODEL_NAME "Necromanser"
#define NECROMANCER_MODEL_OBJECTPATH "Monster"
#define NECROMANCER_MODEL_TEXPATH "Monster/Necromanser"
#define NECROMANCER_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.3f)
#define NECROMANCER_MODEL_TYPE Object_Monster
#define NECROMANCER_MODEL_COLLIDERTYPE Collider_Box
#define NECROMANCER_MODEL_MASS 40
#define NECROMANCER_MODEL_SCALE XMFLOAT3(18,18,18)
#define NECROMANCER_MODEL_RENDERLAYER RenderLayer::Render_Skinned
#define NECROMANCER_MODEL_SHADOW true

#endif