#ifndef EFFECTDATA_H

#define EFFECTDATA_H

#include "../Common/Header/D3DUtil.h"
#include "../Common/Header/Struct.h"
#include "../DirectXRendering/Header/Global.h"

using namespace DirectX;


// È¿°ú ÀÌÆåÆ® ¸ðµ¨
#define BLOOD1_EFFECT_MODEL_NAME "blood1"
#define BLOOD1_EFFECT_MODEL_OBJECTPATH "Effect"
#define BLOOD1_EFFECT_MODEL_TEXPATH "Blood"
#define BLOOD1_EFFECT_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define BLOOD1_EFFECT_MODEL_TYPE Object_Effect
#define BLOOD1_EFFECT_MODEL_COLLIDERTYPE Collider_None
#define BLOOD1_EFFECT_MODEL_MASS 10
#define BLOOD1_EFFECT_MODEL_SCALE XMFLOAT3(1,1,1)
#define BLOOD1_EFFECT_MODEL_RENDERLAYER RenderLayer::Render_Effect;
#define BLOOD1_EFFECT_MODEL_SHADOW false

#define BLOOD2_EFFECT_MODEL_NAME "blood2"
#define BLOOD2_EFFECT_MODEL_OBJECTPATH "Effect"
#define BLOOD2_EFFECT_MODEL_TEXPATH "Blood"
#define BLOOD2_EFFECT_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define BLOOD2_EFFECT_MODEL_TYPE Object_Effect
#define BLOOD2_EFFECT_MODEL_COLLIDERTYPE Collider_None
#define BLOOD2_EFFECT_MODEL_MASS 10
#define BLOOD2_EFFECT_MODEL_SCALE XMFLOAT3(1,1,1)
#define BLOOD2_EFFECT_MODEL_RENDERLAYER RenderLayer::Render_Effect;
#define BLOOD2_EFFECT_MODEL_SHADOW false

#define BLOOD3_EFFECT_MODEL_NAME "blood3"
#define BLOOD3_EFFECT_MODEL_OBJECTPATH "Effect"
#define BLOOD3_EFFECT_MODEL_TEXPATH "Blood"
#define BLOOD3_EFFECT_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define BLOOD3_EFFECT_MODEL_TYPE Object_Effect
#define BLOOD3_EFFECT_MODEL_COLLIDERTYPE Collider_None
#define BLOOD3_EFFECT_MODEL_MASS 10
#define BLOOD3_EFFECT_MODEL_SCALE XMFLOAT3(1,1,1)
#define BLOOD3_EFFECT_MODEL_RENDERLAYER RenderLayer::Render_Effect;
#define BLOOD3_EFFECT_MODEL_SHADOW false

#define BLOOD4_EFFECT_MODEL_NAME "blood4"
#define BLOOD4_EFFECT_MODEL_OBJECTPATH "Effect"
#define BLOOD4_EFFECT_MODEL_TEXPATH "Blood"
#define BLOOD4_EFFECT_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define BLOOD4_EFFECT_MODEL_TYPE Object_Effect
#define BLOOD4_EFFECT_MODEL_COLLIDERTYPE Collider_None
#define BLOOD4_EFFECT_MODEL_MASS 10
#define BLOOD4_EFFECT_MODEL_SCALE XMFLOAT3(1,1,1)
#define BLOOD4_EFFECT_MODEL_RENDERLAYER RenderLayer::Render_Effect;
#define BLOOD4_EFFECT_MODEL_SHADOW false

#define BLOOD5_EFFECT_MODEL_NAME "blood5"
#define BLOOD5_EFFECT_MODEL_OBJECTPATH "Effect"
#define BLOOD5_EFFECT_MODEL_TEXPATH "Blood"
#define BLOOD5_EFFECT_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define BLOOD5_EFFECT_MODEL_TYPE Object_Effect
#define BLOOD5_EFFECT_MODEL_COLLIDERTYPE Collider_None
#define BLOOD5_EFFECT_MODEL_MASS 10
#define BLOOD5_EFFECT_MODEL_SCALE XMFLOAT3(1,1,1)
#define BLOOD5_EFFECT_MODEL_RENDERLAYER RenderLayer::Render_Effect;
#define BLOOD5_EFFECT_MODEL_SHADOW false

#define BLOOD6_EFFECT_MODEL_NAME "blood6"
#define BLOOD6_EFFECT_MODEL_OBJECTPATH "Effect"
#define BLOOD6_EFFECT_MODEL_TEXPATH "Blood"
#define BLOOD6_EFFECT_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define BLOOD6_EFFECT_MODEL_TYPE Object_Effect
#define BLOOD6_EFFECT_MODEL_COLLIDERTYPE Collider_None
#define BLOOD6_EFFECT_MODEL_MASS 10
#define BLOOD6_EFFECT_MODEL_SCALE XMFLOAT3(1,1,1)
#define BLOOD6_EFFECT_MODEL_RENDERLAYER RenderLayer::Render_Effect;
#define BLOOD6_EFFECT_MODEL_SHADOW false

#define BLOOD7_EFFECT_MODEL_NAME "blood7"
#define BLOOD7_EFFECT_MODEL_OBJECTPATH "Effect"
#define BLOOD7_EFFECT_MODEL_TEXPATH "Blood"
#define BLOOD7_EFFECT_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define BLOOD7_EFFECT_MODEL_TYPE Object_Effect
#define BLOOD7_EFFECT_MODEL_COLLIDERTYPE Collider_None
#define BLOOD7_EFFECT_MODEL_MASS 10
#define BLOOD7_EFFECT_MODEL_SCALE XMFLOAT3(1,1,1)
#define BLOOD7_EFFECT_MODEL_RENDERLAYER RenderLayer::Render_Effect;
#define BLOOD7_EFFECT_MODEL_SHADOW false


#endif