#ifndef INSIDEOBJECTDATA_H

#define INSIDEOBJECTDATA_H

#include "../Common/Header/D3DUtil.h"
#include "../Common/Header/Struct.h"
#include "../DirectXRendering/Header/Global.h"

using namespace DirectX;

#define BED_MODEL_NAME "Bed"
#define BED_MODEL_OBJECTPATH "WorldObject/Inside"
#define BED_MODEL_TEXPATH "WorldObject/Inside/Bed"
#define BED_MODEL_EXTENTS XMFLOAT3(0.45f, 0.4f, 1.25f)
#define BED_MODEL_TYPE Object_Movable
#define BED_MODEL_COLLIDERTYPE Collider_Box
#define BED_MODEL_MASS 10
#define BED_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define BED_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BED_MODEL_SHADOW true

#define BED_FEATHER_MODEL_NAME "BedFeather"
#define BED_FEATHER_MODEL_OBJECTPATH "WorldObject/Inside"
#define BED_FEATHER_MODEL_TEXPATH "WorldObject/Inside/Bed"
#define BED_FEATHER_MODEL_EXTENTS XMFLOAT3(0.4f, 0.02f, 0.575f)
#define BED_FEATHER_MODEL_TYPE Object_Movable
#define BED_FEATHER_MODEL_COLLIDERTYPE Collider_Box
#define BED_FEATHER_MODEL_MASS 2
#define BED_FEATHER_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define BED_FEATHER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BED_FEATHER_MODEL_SHADOW true

#define BEDROOM_FACING_MODEL_NAME "Bedroom_facing"
#define BEDROOM_FACING_MODEL_OBJECTPATH "WorldObject/Inside"
#define BEDROOM_FACING_MODEL_TEXPATH "WorldObject/Inside/Tiles"
#define BEDROOM_FACING_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define BEDROOM_FACING_MODEL_TYPE Object_World
#define BEDROOM_FACING_MODEL_COLLIDERTYPE Collider_None
#define BEDROOM_FACING_MODEL_MASS 9999
#define BEDROOM_FACING_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define BEDROOM_FACING_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BEDROOM_FACING_MODEL_SHADOW false

#define BEDROOM_FLOOR_MODEL_NAME "Bedroom_floor"
#define BEDROOM_FLOOR_MODEL_OBJECTPATH "WorldObject/Inside"
#define BEDROOM_FLOOR_MODEL_TEXPATH "WorldObject/Inside/Tiles"
#define BEDROOM_FLOOR_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define BEDROOM_FLOOR_MODEL_TYPE Object_World
#define BEDROOM_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define BEDROOM_FLOOR_MODEL_MASS 9999
#define BEDROOM_FLOOR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define BEDROOM_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BEDROOM_FLOOR_MODEL_SHADOW false

#define BLACK_PLANE_MODEL_NAME "BlackPlane"
#define BLACK_PLANE_MODEL_OBJECTPATH "WorldObject/Inside"
#define BLACK_PLANE_MODEL_TEXPATH ""
#define BLACK_PLANE_MODEL_EXTENTS XMFLOAT3(2.5f, 0.1f, 2.5f)
#define BLACK_PLANE_MODEL_TYPE Object_World
#define BLACK_PLANE_MODEL_COLLIDERTYPE Collider_Box
#define BLACK_PLANE_MODEL_MASS 9999
#define BLACK_PLANE_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define BLACK_PLANE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BLACK_PLANE_MODEL_SHADOW false

#define BOARD_MODEL_NAME "Board"
#define BOARD_MODEL_OBJECTPATH "WorldObject/Inside"
#define BOARD_MODEL_TEXPATH "WorldObject/Inside/Board"
#define BOARD_MODEL_EXTENTS XMFLOAT3(2.2f, 1.15f, 0.3f)
#define BOARD_MODEL_TYPE Object_World
#define BOARD_MODEL_COLLIDERTYPE Collider_Box
#define BOARD_MODEL_MASS 9999
#define BOARD_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define BOARD_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BOARD_MODEL_SHADOW true

#define CASEMETALIC_MODEL_NAME "CaseMetallic"
#define CASEMETALIC_MODEL_OBJECTPATH "WorldObject/Inside"
#define CASEMETALIC_MODEL_TEXPATH "WorldObject/Inside/MetalicCase"
#define CASEMETALIC_MODEL_EXTENTS XMFLOAT3(0.6f, 1.05f, 0.28f)
#define CASEMETALIC_MODEL_TYPE Object_Movable
#define CASEMETALIC_MODEL_COLLIDERTYPE Collider_Box
#define CASEMETALIC_MODEL_MASS 15
#define CASEMETALIC_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define CASEMETALIC_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CASEMETALIC_MODEL_SHADOW true

#define CHAIR_LEATHER_MODEL_NAME "ChairLeather"
#define CHAIR_LEATHER_MODEL_OBJECTPATH "WorldObject/Inside"
#define CHAIR_LEATHER_MODEL_TEXPATH "WorldObject/Inside/Chair"
#define CHAIR_LEATHER_MODEL_EXTENTS XMFLOAT3(0.22f, 0.45f, 0.35f)
#define CHAIR_LEATHER_MODEL_TYPE Object_Movable
#define CHAIR_LEATHER_MODEL_COLLIDERTYPE Collider_Box
#define CHAIR_LEATHER_MODEL_MASS 5
#define CHAIR_LEATHER_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define CHAIR_LEATHER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CHAIR_LEATHER_MODEL_SHADOW true

#define CHAIR_SCHOOL_MODEL_NAME "ChairSchool"
#define CHAIR_SCHOOL_MODEL_OBJECTPATH "WorldObject/Inside"
#define CHAIR_SCHOOL_MODEL_TEXPATH "WorldObject/Inside/Chair"
#define CHAIR_SCHOOL_MODEL_EXTENTS XMFLOAT3(0.22f, 0.45f, 0.35f)
#define CHAIR_SCHOOL_MODEL_TYPE Object_Movable
#define CHAIR_SCHOOL_MODEL_COLLIDERTYPE Collider_Box
#define CHAIR_SCHOOL_MODEL_MASS 5
#define CHAIR_SCHOOL_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define CHAIR_SCHOOL_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CHAIR_SCHOOL_MODEL_SHADOW true

#define CHAIR_WHITE_MODEL_NAME "ChairWhite"
#define CHAIR_WHITE_MODEL_OBJECTPATH "WorldObject/Inside"
#define CHAIR_WHITE_MODEL_TEXPATH "WorldObject/Inside/Chair"
#define CHAIR_WHITE_MODEL_EXTENTS XMFLOAT3(0.22f, 0.45f, 0.35f)
#define CHAIR_WHITE_MODEL_TYPE Object_Movable
#define CHAIR_WHITE_MODEL_COLLIDERTYPE Collider_Box
#define CHAIR_WHITE_MODEL_MASS 5
#define CHAIR_WHITE_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define CHAIR_WHITE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CHAIR_WHITE_MODEL_SHADOW true

#define CLASSROOM_FLOOR_MODEL_NAME "Classroom_floor"
#define CLASSROOM_FLOOR_MODEL_OBJECTPATH "WorldObject/Inside"
#define CLASSROOM_FLOOR_MODEL_TEXPATH "WorldObject/Inside/Wall"
#define CLASSROOM_FLOOR_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define CLASSROOM_FLOOR_MODEL_TYPE Object_World
#define CLASSROOM_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define CLASSROOM_FLOOR_MODEL_MASS 9999
#define CLASSROOM_FLOOR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define CLASSROOM_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CLASSROOM_FLOOR_MODEL_SHADOW false

#define CURTAIN_MEDIC_MODEL_NAME "CurtainsMedic"
#define CURTAIN_MEDIC_MODEL_OBJECTPATH "WorldObject/Inside"
#define CURTAIN_MEDIC_MODEL_TEXPATH "WorldObject/Inside/Curtain"
#define CURTAIN_MEDIC_MODEL_EXTENTS XMFLOAT3(0.9f, 1.0f, 0.35f)
#define CURTAIN_MEDIC_MODEL_TYPE Object_Movable
#define CURTAIN_MEDIC_MODEL_COLLIDERTYPE Collider_Box
#define CURTAIN_MEDIC_MODEL_MASS 15
#define CURTAIN_MEDIC_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define CURTAIN_MEDIC_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CURTAIN_MEDIC_MODEL_SHADOW true

#define DINNING_FLOOR_MODEL_NAME "Dinning_floor"
#define DINNING_FLOOR_MODEL_OBJECTPATH "WorldObject/Inside"
#define DINNING_FLOOR_MODEL_TEXPATH "WorldObject/Inside/Tiles"
#define DINNING_FLOOR_MODEL_EXTENTS XMFLOAT3(0,0,0)
#define DINNING_FLOOR_MODEL_TYPE Object_World
#define DINNING_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define DINNING_FLOOR_MODEL_MASS 9999
#define DINNING_FLOOR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define DINNING_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DINNING_FLOOR_MODEL_SHADOW false

#define DOOR_MODEL_NAME "Door"
#define DOOR_MODEL_OBJECTPATH "WorldObject/Inside"
#define DOOR_MODEL_TEXPATH "WorldObject/Inside/Door"
#define DOOR_MODEL_EXTENTS XMFLOAT3(0.95f, 1.6f, 0.15f)
#define DOOR_MODEL_TYPE Object_World
#define DOOR_MODEL_COLLIDERTYPE Collider_Box
#define DOOR_MODEL_MASS 9999
#define DOOR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define DOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DOOR_MODEL_SHADOW true

#define DOOR_V3_MODEL_NAME "Door_V3"
#define DOOR_V3_MODEL_OBJECTPATH "WorldObject/Inside"
#define DOOR_V3_MODEL_TEXPATH "WorldObject/Inside/Door"
#define DOOR_V3_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define DOOR_V3_MODEL_TYPE Object_World
#define DOOR_V3_MODEL_COLLIDERTYPE Collider_None
#define DOOR_V3_MODEL_MASS 9999
#define DOOR_V3_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define DOOR_V3_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DOOR_V3_MODEL_SHADOW false

#define DOORD_V1_MODEL_NAME "DoorD_V1"
#define DOORD_V1_MODEL_OBJECTPATH "WorldObject/Inside"
#define DOORD_V1_MODEL_TEXPATH "WorldObject/Inside/Door"
#define DOORD_V1_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define DOORD_V1_MODEL_TYPE Object_World
#define DOORD_V1_MODEL_COLLIDERTYPE Collider_None
#define DOORD_V1_MODEL_MASS 9999
#define DOORD_V1_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define DOORD_V1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DOORD_V1_MODEL_SHADOW false

#define DOORD_V2_FRAME_MODEL_NAME "DoorD_V2_Frame"
#define DOORD_V2_FRAME_MODEL_OBJECTPATH "WorldObject/Inside"
#define DOORD_V2_FRAME_MODEL_TEXPATH "WorldObject/Inside/Door"
#define DOORD_V2_FRAME_MODEL_EXTENTS XMFLOAT3(0.0f, 1.0f, 0.0f)
#define DOORD_V2_FRAME_MODEL_TYPE Object_World
#define DOORD_V2_FRAME_MODEL_COLLIDERTYPE Collider_None
#define DOORD_V2_FRAME_MODEL_MASS 9999
#define DOORD_V2_FRAME_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define DOORD_V2_FRAME_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DOORD_V2_FRAME_MODEL_SHADOW true

#define DOORD_V2_LEFT_MODEL_NAME "DoorD_V2_Left"
#define DOORD_V2_LEFT_MODEL_OBJECTPATH "WorldObject/Inside"
#define DOORD_V2_LEFT_MODEL_TEXPATH "WorldObject/Inside/Door"
#define DOORD_V2_LEFT_MODEL_EXTENTS XMFLOAT3(0.45f, 1.05f, 0.05f)
#define DOORD_V2_LEFT_MODEL_TYPE Object_World
#define DOORD_V2_LEFT_MODEL_COLLIDERTYPE Collider_Box
#define DOORD_V2_LEFT_MODEL_MASS 9999
#define DOORD_V2_LEFT_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define DOORD_V2_LEFT_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DOORD_V2_LEFT_MODEL_SHADOW true

#define DOORD_V2_RIGHT_MODEL_NAME "DoorD_V2_Right"
#define DOORD_V2_RIGHT_MODEL_OBJECTPATH "WorldObject/Inside"
#define DOORD_V2_RIGHT_MODEL_TEXPATH "WorldObject/Inside/Door"
#define DOORD_V2_RIGHT_MODEL_EXTENTS XMFLOAT3(0.45f, 1.05f, 0.05f)
#define DOORD_V2_RIGHT_MODEL_TYPE Object_World
#define DOORD_V2_RIGHT_MODEL_COLLIDERTYPE Collider_Box
#define DOORD_V2_RIGHT_MODEL_MASS 9999
#define DOORD_V2_RIGHT_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define DOORD_V2_RIGHT_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DOORD_V2_RIGHT_MODEL_SHADOW true

#define HEATER_MODEL_NAME "Heater"
#define HEATER_MODEL_OBJECTPATH "WorldObject/Inside"
#define HEATER_MODEL_TEXPATH "WorldObject/Inside/Heater"
#define HEATER_MODEL_EXTENTS XMFLOAT3(0.8f, 0.5f, 0.125f)
#define HEATER_MODEL_TYPE Object_World
#define HEATER_MODEL_COLLIDERTYPE Collider_Box
#define HEATER_MODEL_MASS 9999
#define HEATER_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define HEATER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define HEATER_MODEL_SHADOW true

#define INSIDE_FLOOR_MODEL_NAME "InsideFloor"
#define INSIDE_FLOOR_MODEL_OBJECTPATH "WorldObject/Inside"
#define INSIDE_FLOOR_MODEL_TEXPATH "WorldObject/Inside/Floor"
#define INSIDE_FLOOR_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define INSIDE_FLOOR_MODEL_TYPE Object_World
#define INSIDE_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define INSIDE_FLOOR_MODEL_MASS 9999
#define INSIDE_FLOOR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define INSIDE_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define INSIDE_FLOOR_MODEL_SHADOW false

#define INSIDE_ROOF_MODEL_NAME "InsideRoof"
#define INSIDE_ROOF_MODEL_OBJECTPATH "WorldObject/Inside"
#define INSIDE_ROOF_MODEL_TEXPATH "WorldObject/Inside/Wall"
#define INSIDE_ROOF_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define INSIDE_ROOF_MODEL_TYPE Object_World
#define INSIDE_ROOF_MODEL_COLLIDERTYPE Collider_None
#define INSIDE_ROOF_MODEL_MASS 9999
#define INSIDE_ROOF_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define INSIDE_ROOF_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define INSIDE_ROOF_MODEL_SHADOW false

#define MATTRESS_MODEL_NAME "Mattress"
#define MATTRESS_MODEL_OBJECTPATH "WorldObject/Inside"
#define MATTRESS_MODEL_TEXPATH "WorldObject/Inside/Bed"
#define MATTRESS_MODEL_EXTENTS XMFLOAT3(0.45f, 0.05f, 1.0f)
#define MATTRESS_MODEL_TYPE Object_Movable
#define MATTRESS_MODEL_COLLIDERTYPE Collider_Box
#define MATTRESS_MODEL_MASS 5
#define MATTRESS_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define MATTRESS_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MATTRESS_MODEL_SHADOW true

#define MEDRACK_MODEL_NAME "MedRack"
#define MEDRACK_MODEL_OBJECTPATH "WorldObject/Inside"
#define MEDRACK_MODEL_TEXPATH "WorldObject/Inside/MedRack"
#define MEDRACK_MODEL_EXTENTS XMFLOAT3(0.65f, 1.05f, 0.4f)
#define MEDRACK_MODEL_TYPE Object_World
#define MEDRACK_MODEL_COLLIDERTYPE Collider_Box
#define MEDRACK_MODEL_MASS 9999
#define MEDRACK_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define MEDRACK_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MEDRACK_MODEL_SHADOW true

#define MORGUE_FLOOR_MODEL_NAME "Morgue_floor"
#define MORGUE_FLOOR_MODEL_OBJECTPATH "WorldObject/Inside"
#define MORGUE_FLOOR_MODEL_TEXPATH "WorldObject/Inside/Tiles"
#define MORGUE_FLOOR_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define MORGUE_FLOOR_MODEL_TYPE Object_World
#define MORGUE_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define MORGUE_FLOOR_MODEL_MASS 9999
#define MORGUE_FLOOR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define MORGUE_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MORGUE_FLOOR_MODEL_SHADOW false

#define MORGUE_BOX_MODEL_NAME "MorgueBox"
#define MORGUE_BOX_MODEL_OBJECTPATH "WorldObject/Inside"
#define MORGUE_BOX_MODEL_TEXPATH "WorldObject/Inside/Morgue"
#define MORGUE_BOX_MODEL_EXTENTS XMFLOAT3(1.125f, 1.3f, 1.4f)
#define MORGUE_BOX_MODEL_TYPE Object_World
#define MORGUE_BOX_MODEL_COLLIDERTYPE Collider_Box
#define MORGUE_BOX_MODEL_MASS 9999
#define MORGUE_BOX_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define MORGUE_BOX_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MORGUE_BOX_MODEL_SHADOW true

#define MORGUE_TABLE_MODEL_NAME "MorgueTable"
#define MORGUE_TABLE_MODEL_OBJECTPATH "WorldObject/Inside"
#define MORGUE_TABLE_MODEL_TEXPATH "WorldObject/Inside/Morgue"
#define MORGUE_TABLE_MODEL_EXTENTS XMFLOAT3(1.125f, 0.45f, 0.6f)
#define MORGUE_TABLE_MODEL_TYPE Object_Movable
#define MORGUE_TABLE_MODEL_COLLIDERTYPE Collider_Box
#define MORGUE_TABLE_MODEL_MASS 10
#define MORGUE_TABLE_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define MORGUE_TABLE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MORGUE_TABLE_MODEL_SHADOW true

#define MORGUE_WHEEL_BED_MODEL_NAME "MorgueWheelBed"
#define MORGUE_WHEEL_BED_MODEL_OBJECTPATH "WorldObject/Inside"
#define MORGUE_WHEEL_BED_MODEL_TEXPATH "WorldObject/Inside/Morgue"
#define MORGUE_WHEEL_BED_MODEL_EXTENTS XMFLOAT3(1.125f, 0.45f, 0.5f)
#define MORGUE_WHEEL_BED_MODEL_TYPE Object_Movable
#define MORGUE_WHEEL_BED_MODEL_COLLIDERTYPE Collider_Box
#define MORGUE_WHEEL_BED_MODEL_MASS 10
#define MORGUE_WHEEL_BED_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define MORGUE_WHEEL_BED_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MORGUE_WHEEL_BED_MODEL_SHADOW true

#define NEONLAMP_MODEL_NAME "NeonLamp"
#define NEONLAMP_MODEL_OBJECTPATH "WorldObject/Inside"
#define NEONLAMP_MODEL_TEXPATH "WorldObject/Inside/Light"
#define NEONLAMP_MODEL_EXTENTS XMFLOAT3(0.0f, 0.1f, 0.0f)
#define NEONLAMP_MODEL_TYPE Object_World
#define NEONLAMP_MODEL_COLLIDERTYPE Collider_None
#define NEONLAMP_MODEL_MASS 9999
#define NEONLAMP_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define NEONLAMP_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define NEONLAMP_MODEL_SHADOW false

#define PILLOW_MODEL_NAME "Pillow"
#define PILLOW_MODEL_OBJECTPATH "WorldObject/Inside"
#define PILLOW_MODEL_TEXPATH "WorldObject/Inside/Bed"
#define PILLOW_MODEL_EXTENTS XMFLOAT3(0.3f, 0.05f, 0.2f)
#define PILLOW_MODEL_TYPE Object_Movable
#define PILLOW_MODEL_COLLIDERTYPE Collider_Box
#define PILLOW_MODEL_MASS 3
#define PILLOW_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define PILLOW_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define PILLOW_MODEL_SHADOW true

#define POSTER_MODEL_NAME "PosterHuman"
#define POSTER_MODEL_OBJECTPATH "WorldObject/Inside"
#define POSTER_MODEL_TEXPATH "WorldObject/Inside/Poster"
#define POSTER_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define POSTER_MODEL_TYPE Object_World
#define POSTER_MODEL_COLLIDERTYPE Collider_None
#define POSTER_MODEL_MASS 9999
#define POSTER_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define POSTER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define POSTER_MODEL_SHADOW false

#define SINGLE_LIGHT_MODEL_NAME "SingleLight"
#define SINGLE_LIGHT_MODEL_OBJECTPATH "WorldObject/Inside"
#define SINGLE_LIGHT_MODEL_TEXPATH "WorldObject/Inside/Light"
#define SINGLE_LIGHT_MODEL_EXTENTS XMFLOAT3(0.0f, 0.3f, 0.0f)
#define SINGLE_LIGHT_MODEL_TYPE Object_World
#define SINGLE_LIGHT_MODEL_COLLIDERTYPE Collider_None
#define SINGLE_LIGHT_MODEL_MASS 9999
#define SINGLE_LIGHT_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define SINGLE_LIGHT_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define SINGLE_LIGHT_MODEL_SHADOW false

#define SINK_MODEL_NAME "Sink"
#define SINK_MODEL_OBJECTPATH "WorldObject/Inside"
#define SINK_MODEL_TEXPATH "WorldObject/Inside/Sink"
#define SINK_MODEL_EXTENTS XMFLOAT3(0.3f, 0.3f, 0.275f)
#define SINK_MODEL_TYPE Object_World
#define SINK_MODEL_COLLIDERTYPE Collider_Box
#define SINK_MODEL_MASS 9999
#define SINK_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define SINK_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define SINK_MODEL_SHADOW true

#define STOCK_FLOOR_MODEL_NAME "Stock_floor"
#define STOCK_FLOOR_MODEL_OBJECTPATH "WorldObject/Inside"
#define STOCK_FLOOR_MODEL_TEXPATH "WorldObject/Inside/Wall"
#define STOCK_FLOOR_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define STOCK_FLOOR_MODEL_TYPE Object_World
#define STOCK_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define STOCK_FLOOR_MODEL_MASS 9999
#define STOCK_FLOOR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define STOCK_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define STOCK_FLOOR_MODEL_SHADOW false

#define SURGERY_TABLE_MODEL_NAME "SurgeryTable"
#define SURGERY_TABLE_MODEL_OBJECTPATH "WorldObject/Inside"
#define SURGERY_TABLE_MODEL_TEXPATH "WorldObject/Inside/Surgery"
#define SURGERY_TABLE_MODEL_EXTENTS XMFLOAT3(0.275f, 0.35f, 0.3f)
#define SURGERY_TABLE_MODEL_TYPE Object_Movable
#define SURGERY_TABLE_MODEL_COLLIDERTYPE Collider_Box
#define SURGERY_TABLE_MODEL_MASS 10
#define SURGERY_TABLE_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define SURGERY_TABLE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define SURGERY_TABLE_MODEL_SHADOW true

#define SURGERY_WHEEL_BAD_MODEL_NAME "SurgeryWheelBad"
#define SURGERY_WHEEL_BAD_MODEL_OBJECTPATH "WorldObject/Inside"
#define SURGERY_WHEEL_BAD_MODEL_TEXPATH "WorldObject/Inside/Surgery"
#define SURGERY_WHEEL_BAD_MODEL_EXTENTS XMFLOAT3(0.45f, 0.35f, 1.0f)
#define SURGERY_WHEEL_BAD_MODEL_TYPE Object_Movable
#define SURGERY_WHEEL_BAD_MODEL_COLLIDERTYPE Collider_Box
#define SURGERY_WHEEL_BAD_MODEL_MASS 10
#define SURGERY_WHEEL_BAD_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define SURGERY_WHEEL_BAD_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define SURGERY_WHEEL_BAD_MODEL_SHADOW true

#define SUSPENSION_MODEL_NAME "Suspension"
#define SUSPENSION_MODEL_OBJECTPATH "WorldObject/Inside"
#define SUSPENSION_MODEL_TEXPATH "WorldObject/Inside/Curtain"
#define SUSPENSION_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define SUSPENSION_MODEL_TYPE Object_World
#define SUSPENSION_MODEL_COLLIDERTYPE Collider_None
#define SUSPENSION_MODEL_MASS 9999
#define SUSPENSION_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define SUSPENSION_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define SUSPENSION_MODEL_SHADOW false

#define TABLE_BED_MODEL_NAME "Table_Bed"
#define TABLE_BED_MODEL_OBJECTPATH "WorldObject/Inside"
#define TABLE_BED_MODEL_TEXPATH "WorldObject/Inside/Table"
#define TABLE_BED_MODEL_EXTENTS XMFLOAT3(0.275f, 0.35f, 0.35f)
#define TABLE_BED_MODEL_TYPE Object_Movable
#define TABLE_BED_MODEL_COLLIDERTYPE Collider_Box
#define TABLE_BED_MODEL_MASS 5
#define TABLE_BED_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define TABLE_BED_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define TABLE_BED_MODEL_SHADOW true

#define TABLE_SCHOOL_MODEL_NAME "TableSchool"
#define TABLE_SCHOOL_MODEL_OBJECTPATH "WorldObject/Inside"
#define TABLE_SCHOOL_MODEL_TEXPATH "WorldObject/Inside/Table"
#define TABLE_SCHOOL_MODEL_EXTENTS XMFLOAT3(0.55f, 0.4f, 0.35f)
#define TABLE_SCHOOL_MODEL_TYPE Object_Movable
#define TABLE_SCHOOL_MODEL_COLLIDERTYPE Collider_Box
#define TABLE_SCHOOL_MODEL_MASS 10
#define TABLE_SCHOOL_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define TABLE_SCHOOL_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define TABLE_SCHOOL_MODEL_SHADOW true

#define TABLE_WHITE_MODEL_NAME "TableWhite"
#define TABLE_WHITE_MODEL_OBJECTPATH "WorldObject/Inside"
#define TABLE_WHITE_MODEL_TEXPATH "WorldObject/Inside/Table"
#define TABLE_WHITE_MODEL_EXTENTS XMFLOAT3(0.7f, 0.42f, 0.45f)
#define TABLE_WHITE_MODEL_TYPE Object_Movable
#define TABLE_WHITE_MODEL_COLLIDERTYPE Collider_Box
#define TABLE_WHITE_MODEL_MASS 10
#define TABLE_WHITE_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define TABLE_WHITE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define TABLE_WHITE_MODEL_SHADOW true

#define TABLE_WHITE_KITCHEN_MODEL_NAME "TableWhiteKitchen"
#define TABLE_WHITE_KITCHEN_MODEL_OBJECTPATH "WorldObject/Inside"
#define TABLE_WHITE_KITCHEN_MODEL_TEXPATH "WorldObject/Inside/Table"
#define TABLE_WHITE_KITCHEN_MODEL_EXTENTS XMFLOAT3(0.7f, 0.42f, 0.7f)
#define TABLE_WHITE_KITCHEN_MODEL_TYPE Object_Movable
#define TABLE_WHITE_KITCHEN_MODEL_COLLIDERTYPE Collider_Box
#define TABLE_WHITE_KITCHEN_MODEL_MASS 10
#define TABLE_WHITE_KITCHEN_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define TABLE_WHITE_KITCHEN_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define TABLE_WHITE_KITCHEN_MODEL_SHADOW true

#define TAP_MODEL_NAME "Tap"
#define TAP_MODEL_OBJECTPATH "WorldObject/Inside"
#define TAP_MODEL_TEXPATH "WorldObject/Inside/Sink"
#define TAP_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define TAP_MODEL_TYPE Object_World
#define TAP_MODEL_COLLIDERTYPE Collider_None
#define TAP_MODEL_MASS 9999
#define TAP_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define TAP_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define TAP_MODEL_SHADOW true

#define WALL_MODEL_NAME "Wall"
#define WALL_MODEL_OBJECTPATH "WorldObject/Inside"
#define WALL_MODEL_TEXPATH "WorldObject/Inside/Wall"
#define WALL_MODEL_EXTENTS XMFLOAT3(3.7f, 2.0f, 0.1f)
#define WALL_MODEL_TYPE Object_World
#define WALL_MODEL_COLLIDERTYPE Collider_Box
#define WALL_MODEL_MASS 9999
#define WALL_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WALL_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WALL_MODEL_SHADOW true

#define WALL2_MODEL_NAME "Wall2"
#define WALL2_MODEL_OBJECTPATH "WorldObject/Inside"
#define WALL2_MODEL_TEXPATH "WorldObject/Inside/Wall"
#define WALL2_MODEL_EXTENTS XMFLOAT3(0.75f, 2.0f, 0.28f)
#define WALL2_MODEL_TYPE Object_World
#define WALL2_MODEL_COLLIDERTYPE Collider_Box
#define WALL2_MODEL_MASS 9999
#define WALL2_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WALL2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WALL2_MODEL_SHADOW true

#define WALL_HALF_MODEL_NAME "Wall_Half"
#define WALL_HALF_MODEL_OBJECTPATH "WorldObject/Inside"
#define WALL_HALF_MODEL_TEXPATH "WorldObject/Inside/Wall"
#define WALL_HALF_MODEL_EXTENTS XMFLOAT3(1.85f, 2.0f, 0.1f)
#define WALL_HALF_MODEL_TYPE Object_World
#define WALL_HALF_MODEL_COLLIDERTYPE Collider_Box
#define WALL_HALF_MODEL_MASS 9999
#define WALL_HALF_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WALL_HALF_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WALL_HALF_MODEL_SHADOW true

#define WALL_DOORWAY_MODEL_NAME "WallDoorWay"
#define WALL_DOORWAY_MODEL_OBJECTPATH "WorldObject/Inside"
#define WALL_DOORWAY_MODEL_TEXPATH "WorldObject/Inside/Wall"
#define WALL_DOORWAY_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define WALL_DOORWAY_MODEL_TYPE Object_World
#define WALL_DOORWAY_MODEL_COLLIDERTYPE Collider_None
#define WALL_DOORWAY_MODEL_MASS 9999
#define WALL_DOORWAY_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WALL_DOORWAY_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WALL_DOORWAY_MODEL_SHADOW true

#define WHEEL_CHAIR_MODEL_NAME "WheelChair"
#define WHEEL_CHAIR_MODEL_OBJECTPATH "WorldObject/Inside"
#define WHEEL_CHAIR_MODEL_TEXPATH "WorldObject/Inside/Chair"
#define WHEEL_CHAIR_MODEL_EXTENTS XMFLOAT3(0.3f, 0.55f, 0.56f)
#define WHEEL_CHAIR_MODEL_TYPE Object_Movable
#define WHEEL_CHAIR_MODEL_COLLIDERTYPE Collider_Box
#define WHEEL_CHAIR_MODEL_MASS 10
#define WHEEL_CHAIR_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WHEEL_CHAIR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WHEEL_CHAIR_MODEL_SHADOW true

#define WINDOW_MODEL_NAME "Window"
#define WINDOW_MODEL_OBJECTPATH "WorldObject/Inside"
#define WINDOW_MODEL_TEXPATH "WorldObject/Hospital"
#define WINDOW_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define WINDOW_MODEL_TYPE Object_World
#define WINDOW_MODEL_COLLIDERTYPE Collider_None
#define WINDOW_MODEL_MASS 9999
#define WINDOW_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WINDOW_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WINDOW_MODEL_SHADOW false

#define WINDOW_BARRIER_MODEL_NAME "Window_Barrier"
#define WINDOW_BARRIER_MODEL_OBJECTPATH "WorldObject/Inside"
#define WINDOW_BARRIER_MODEL_TEXPATH "WorldObject/Inside/Window"
#define WINDOW_BARRIER_MODEL_EXTENTS XMFLOAT3(0.0f, 0.0f, 0.0f)
#define WINDOW_BARRIER_MODEL_TYPE Object_World
#define WINDOW_BARRIER_MODEL_COLLIDERTYPE Collider_None
#define WINDOW_BARRIER_MODEL_MASS 9999
#define WINDOW_BARRIER_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WINDOW_BARRIER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WINDOW_BARRIER_MODEL_SHADOW false

#define WINDOW_HALL_MODEL_NAME "WindowHall"
#define WINDOW_HALL_MODEL_OBJECTPATH "WorldObject/Inside"
#define WINDOW_HALL_MODEL_TEXPATH "WorldObject/Inside/Window"
#define WINDOW_HALL_MODEL_EXTENTS XMFLOAT3(0.75f, 0.75f, 0.0f)
#define WINDOW_HALL_MODEL_TYPE Object_World
#define WINDOW_HALL_MODEL_COLLIDERTYPE Collider_Box
#define WINDOW_HALL_MODEL_MASS 9999
#define WINDOW_HALL_MODEL_SCALE XMFLOAT3(10.0f, 10.0f, 10.0f)
#define WINDOW_HALL_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WINDOW_HALL_MODEL_SHADOW false



#endif