#ifndef  ITEMANDEVENTDATA_H

#define ITEMANDEVENTDATA_H

#include "../Common/Header/D3DUtil.h"
#include "../Common/Header/Struct.h"
#include "../DirectXRendering/Header/Global.h"

using namespace DirectX;

// 아이템 모델
#define SCOREITEM1_MODEL_NAME "5_Side_Diamond"
#define SCOREITEM1_MODEL_OBJECTPATH "Item"
#define SCOREITEM1_MODEL_TEXPATH ""
#define SCOREITEM1_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.2f)
#define SCOREITEM1_MODEL_TYPE Object_Item
#define SCOREITEM1_MODEL_COLLIDERTYPE Collider_None
#define SCOREITEM1_MODEL_MASS 5
#define SCOREITEM1_MODEL_SCALE XMFLOAT3(1,1,1)
#define SCOREITEM1_MODEL_RENDERLAYER RenderLayer::Render_Static
#define SCOREITEM1_MODEL_SHADOW true

#define SCOREITEM2_MODEL_NAME "Cubie"
#define SCOREITEM2_MODEL_OBJECTPATH "Item"
#define SCOREITEM2_MODEL_TEXPATH ""
#define SCOREITEM2_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.2f)
#define SCOREITEM2_MODEL_TYPE Object_Item
#define SCOREITEM2_MODEL_COLLIDERTYPE Collider_None
#define SCOREITEM2_MODEL_MASS 5
#define SCOREITEM2_MODEL_SCALE XMFLOAT3(1,1,1)
#define SCOREITEM2_MODEL_RENDERLAYER RenderLayer::Render_Static
#define SCOREITEM2_MODEL_SHADOW true

#define SCOREITEM3_MODEL_NAME "Diamondo"
#define SCOREITEM3_MODEL_OBJECTPATH "Item"
#define SCOREITEM3_MODEL_TEXPATH ""
#define SCOREITEM3_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.2f)
#define SCOREITEM3_MODEL_TYPE Object_Item
#define SCOREITEM3_MODEL_COLLIDERTYPE Collider_None
#define SCOREITEM3_MODEL_MASS 5
#define SCOREITEM3_MODEL_SCALE XMFLOAT3(1,1,1)
#define SCOREITEM3_MODEL_RENDERLAYER RenderLayer::Render_Static
#define SCOREITEM3_MODEL_SHADOW true

#define SCOREITEM4_MODEL_NAME "Hexgon"
#define SCOREITEM4_MODEL_OBJECTPATH "Item"
#define SCOREITEM4_MODEL_TEXPATH ""
#define SCOREITEM4_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.2f)
#define SCOREITEM4_MODEL_TYPE Object_Item
#define SCOREITEM4_MODEL_COLLIDERTYPE Collider_None
#define SCOREITEM4_MODEL_MASS 5
#define SCOREITEM4_MODEL_SCALE XMFLOAT3(1,1,1)
#define SCOREITEM4_MODEL_RENDERLAYER RenderLayer::Render_Static
#define SCOREITEM4_MODEL_SHADOW true

#define SCOREITEM5_MODEL_NAME "Penta"
#define SCOREITEM5_MODEL_OBJECTPATH "Item"
#define SCOREITEM5_MODEL_TEXPATH ""
#define SCOREITEM5_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.2f)
#define SCOREITEM5_MODEL_TYPE Object_Item
#define SCOREITEM5_MODEL_COLLIDERTYPE Collider_None
#define SCOREITEM5_MODEL_MASS 5
#define SCOREITEM5_MODEL_SCALE XMFLOAT3(1,1,1)
#define SCOREITEM5_MODEL_RENDERLAYER RenderLayer::Render_Static
#define SCOREITEM5_MODEL_SHADOW true

#define HEALITEM_MODEL_NAME "Heart"
#define HEALITEM_MODEL_OBJECTPATH "Item"
#define HEALITEM_MODEL_TEXPATH ""
#define HEALITEM_MODEL_EXTENTS XMFLOAT3(0.3f, 0.8f, 0.2f)
#define HEALITEM_MODEL_TYPE Object_Item
#define HEALITEM_MODEL_COLLIDERTYPE Collider_None
#define HEALITEM_MODEL_MASS 5
#define HEALITEM_MODEL_SCALE XMFLOAT3(3,3,3)
#define HEALITEM_MODEL_RENDERLAYER RenderLayer::Render_Static
#define HEALITEM_MODEL_SHADOW true


// 이벤트 박스
#define ENTER_BOX_MODEL_NAME "Enter_Object"
#define ENTER_BOX_MODEL_OBJECTPATH ""
#define ENTER_BOX_MODEL_TEXPATH ""
#define ENTER_BOX_MODEL_EXTENTS XMFLOAT3(0.5f, 0.5f, 0.5f)
#define ENTER_BOX_MODEL_TYPE Object_Event
//#define EVENT_BOX_MODEL_COLLIDERTYPE Collider_Box
#define ENTER_BOX_MODEL_COLLIDERTYPE Collider_None
#define ENTER_BOX_MODEL_MASS 9999
#define ENTER_BOX_MODEL_SCALE XMFLOAT3(10,10,10)
#define ENTER_BOX_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define ENTER_BOX_MODEL_SHADOW false

#endif