#ifndef WORLDOBJECTDATA1_H

#define WORLDOBJECTDATA1_H

#include "../Common/Header/D3DUtil.h"
#include "../Common/Header/Struct.h"
#include "../DirectXRendering/Header/Global.h"

using namespace DirectX;

#define GRASS_GROUND_MODEL_NAME "Pod_trava"
#define GRASS_GROUND_MODEL_OBJECTPATH "WorldObject/Outside"
#define GRASS_GROUND_MODEL_TEXPATH "Outside"
#define GRASS_GROUND_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define GRASS_GROUND_MODEL_TYPE Object_World
#define GRASS_GROUND_MODEL_COLLIDERTYPE Collider_None
#define GRASS_GROUND_MODEL_MASS 9999
#define GRASS_GROUND_MODEL_SCALE XMFLOAT3(10,10,10)
#define GRASS_GROUND_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define GRASS_GROUND_MODEL_SHADOW false

#define HOSPITAL_MODEL_NAME "Hospital"
#define HOSPITAL_MODEL_OBJECTPATH "WorldObject/Outside"
#define HOSPITAL_MODEL_TEXPATH "Outside/Hospital"
#define HOSPITAL_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define HOSPITAL_MODEL_TYPE Object_World
#define HOSPITAL_MODEL_COLLIDERTYPE Collider_None
#define HOSPITAL_MODEL_MASS 9999
#define HOSPITAL_MODEL_SCALE XMFLOAT3(10,10,10)
#define HOSPITAL_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define HOSPITAL_MODEL_SHADOW false

#define BARREL1_MODEL_NAME "barrel"
#define BARREL1_MODEL_OBJECTPATH "WorldObject/Outside"
#define BARREL1_MODEL_TEXPATH "Outside/Barrel"
#define BARREL1_MODEL_EXTENTS XMFLOAT3(0.4f, 0.4f, 0.7f)
#define BARREL1_MODEL_TYPE Object_Movable
#define BARREL1_MODEL_COLLIDERTYPE Collider_Box
#define BARREL1_MODEL_MASS 10
#define BARREL1_MODEL_SCALE XMFLOAT3(10,10,10)
#define BARREL1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BARREL1_MODEL_SHADOW true

#define BARREL2_MODEL_NAME "Barrel_v1_LD2"
#define BARREL2_MODEL_OBJECTPATH "WorldObject/Outside"
#define BARREL2_MODEL_TEXPATH "Outside/Barrel"
#define BARREL2_MODEL_EXTENTS XMFLOAT3(0.3f, 0.5f, 0.3f)
#define BARREL2_MODEL_TYPE Object_Movable
#define BARREL2_MODEL_COLLIDERTYPE Collider_Box
#define BARREL2_MODEL_MASS 10
#define BARREL2_MODEL_SCALE XMFLOAT3(10,10,10)
#define BARREL2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BARREL2_MODEL_SHADOW true

#define BARREL3_MODEL_NAME "Barrels_1"
#define BARREL3_MODEL_OBJECTPATH "WorldObject/Outside"
#define BARREL3_MODEL_TEXPATH "Outside/Barrel"
#define BARREL3_MODEL_EXTENTS XMFLOAT3(0.27f, 0.27f, 0.4f)
#define BARREL3_MODEL_TYPE Object_Movable
#define BARREL3_MODEL_COLLIDERTYPE Collider_Box
#define BARREL3_MODEL_MASS 10
#define BARREL3_MODEL_SCALE XMFLOAT3(10,10,10)
#define BARREL3_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BARREL3_MODEL_SHADOW true

#define BARREL4_MODEL_NAME "Barrels_2"
#define BARREL4_MODEL_OBJECTPATH "WorldObject/Outside"
#define BARREL4_MODEL_TEXPATH "Outside/Barrel"
#define BARREL4_MODEL_EXTENTS XMFLOAT3(0.27f, 0.27f, 0.4f)
#define BARREL4_MODEL_TYPE Object_Movable
#define BARREL4_MODEL_COLLIDERTYPE Collider_Box
#define BARREL4_MODEL_MASS 10
#define BARREL4_MODEL_SCALE XMFLOAT3(10,10,10)
#define BARREL4_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BARREL4_MODEL_SHADOW true

#define BARREL5_MODEL_NAME "Barrels_3"
#define BARREL5_MODEL_OBJECTPATH "WorldObject/Outside"
#define BARREL5_MODEL_TEXPATH "Outside/Barrel"
#define BARREL5_MODEL_EXTENTS XMFLOAT3(0.27f, 0.27f, 0.4f)
#define BARREL5_MODEL_TYPE Object_Movable
#define BARREL5_MODEL_COLLIDERTYPE Collider_Box
#define BARREL5_MODEL_MASS 10
#define BARREL5_MODEL_SCALE XMFLOAT3(10,10,10)
#define BARREL5_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BARREL5_MODEL_SHADOW true

#define BENCH_MODEL_NAME "Bench"
#define BENCH_MODEL_OBJECTPATH "WorldObject/Outside"
#define BENCH_MODEL_TEXPATH "Outside/Bench"
#define BENCH_MODEL_EXTENTS XMFLOAT3(0.9f, 0.35f, 0.15f)
#define BENCH_MODEL_TYPE Object_Movable
#define BENCH_MODEL_COLLIDERTYPE Collider_Box
#define BENCH_MODEL_MASS 10
#define BENCH_MODEL_SCALE XMFLOAT3(10,10,10)
#define BENCH_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BENCH_MODEL_SHADOW true

#define BOILER_MODEL_NAME "BigBoiler"
#define BOILER_MODEL_OBJECTPATH "WorldObject/Outside"
#define BOILER_MODEL_TEXPATH "Outside/Big_Boiler"
#define BOILER_MODEL_EXTENTS XMFLOAT3(0.9f, 0.65f, 0.9f)
#define BOILER_MODEL_TYPE Object_World
#define BOILER_MODEL_COLLIDERTYPE Collider_Box
#define BOILER_MODEL_MASS 9999
#define BOILER_MODEL_SCALE XMFLOAT3(10,10,10)
#define BOILER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BOILER_MODEL_SHADOW true

#define BIGSHELF_MODEL_NAME "BigShelf"
#define BIGSHELF_MODEL_OBJECTPATH "WorldObject/Outside"
#define BIGSHELF_MODEL_TEXPATH "Outside/BigShelf"
#define BIGSHELF_MODEL_EXTENTS XMFLOAT3(1.15f, 1.3f, 0.6f)
#define BIGSHELF_MODEL_TYPE Object_World
#define BIGSHELF_MODEL_COLLIDERTYPE Collider_Box
#define BIGSHELF_MODEL_MASS 9999
#define BIGSHELF_MODEL_SCALE XMFLOAT3(10,10,10)
#define BIGSHELF_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BIGSHELF_MODEL_SHADOW true

#define BIGSHELF_STOCK_MODEL_NAME "BigShelf_Stock"
#define BIGSHELF_STOCK_MODEL_OBJECTPATH "WorldObject/Outside"
#define BIGSHELF_STOCK_MODEL_TEXPATH "Outside/BigShelf"
#define BIGSHELF_STOCK_MODEL_EXTENTS XMFLOAT3(0.75, 1.15, 0.4)
#define BIGSHELF_STOCK_MODEL_TYPE Object_World
#define BIGSHELF_STOCK_MODEL_COLLIDERTYPE Collider_Box
#define BIGSHELF_STOCK_MODEL_MASS 9999
#define BIGSHELF_STOCK_MODEL_SCALE XMFLOAT3(10,10,10)
#define BIGSHELF_STOCK_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define BIGSHELF_STOCK_MODEL_SHADOW true

#define WOOD_BOX1_MODEL_NAME "Box_V1"
#define WOOD_BOX1_MODEL_OBJECTPATH "WorldObject/Outside"
#define WOOD_BOX1_MODEL_TEXPATH "Outside/Box"
#define WOOD_BOX1_MODEL_EXTENTS XMFLOAT3(0.25, 0.1, 0.2)
#define WOOD_BOX1_MODEL_TYPE Object_Movable
#define WOOD_BOX1_MODEL_COLLIDERTYPE Collider_Box
#define WOOD_BOX1_MODEL_MASS 5
#define WOOD_BOX1_MODEL_SCALE XMFLOAT3(10,10,10)
#define WOOD_BOX1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WOOD_BOX1_MODEL_SHADOW true

#define CABELS_MODEL_NAME "Cabels"
#define CABELS_MODEL_OBJECTPATH "WorldObject/Outside"
#define CABELS_MODEL_TEXPATH "Outside/Cabels"
#define CABELS_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define CABELS_MODEL_TYPE Object_World
#define CABELS_MODEL_COLLIDERTYPE Collider_None
#define CABELS_MODEL_MASS 9999
#define CABELS_MODEL_SCALE XMFLOAT3(10,10,10)
#define CABELS_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CABELS_MODEL_SHADOW false

#define CAN_MODEL_NAME "CanOld"
#define CAN_MODEL_OBJECTPATH "WorldObject/Outside"
#define CAN_MODEL_TEXPATH "Outside/Can"
#define CAN_MODEL_EXTENTS XMFLOAT3(0.05f, 0.1f, 0.05f)
#define CAN_MODEL_TYPE Object_Movable
#define CAN_MODEL_COLLIDERTYPE Collider_Box
#define CAN_MODEL_MASS 1
#define CAN_MODEL_SCALE XMFLOAT3(10,10,10)
#define CAN_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CAN_MODEL_SHADOW true

#define CAN_DAMAGED_MODEL_NAME "CanOld_Damaged"
#define CAN_DAMAGED_MODEL_OBJECTPATH "WorldObject/Outside"
#define CAN_DAMAGED_MODEL_TEXPATH "Outside/Can"
#define CAN_DAMAGED_MODEL_EXTENTS XMFLOAT3(0.1f, 0.05f, 0.05f)
#define CAN_DAMAGED_MODEL_TYPE Object_Movable
#define CAN_DAMAGED_MODEL_COLLIDERTYPE Collider_Box
#define CAN_DAMAGED_MODEL_MASS 1
#define CAN_DAMAGED_MODEL_SCALE XMFLOAT3(10,10,10)
#define CAN_DAMAGED_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CAN_DAMAGED_MODEL_SHADOW true

#define CONTAINER_MODEL_NAME "Cargo_container_v1_LD1close"
#define CONTAINER_MODEL_OBJECTPATH "WorldObject/Outside"
#define CONTAINER_MODEL_TEXPATH "Outside/Container"
#define CONTAINER_MODEL_EXTENTS XMFLOAT3(4.0f, 1.5f, 1.5f)
#define CONTAINER_MODEL_TYPE Object_World
#define CONTAINER_MODEL_COLLIDERTYPE Collider_Box
#define CONTAINER_MODEL_MASS 9999
#define CONTAINER_MODEL_SCALE XMFLOAT3(10,10,10)
#define CONTAINER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CONTAINER_MODEL_SHADOW true

#define DUMP_CONTAINER_MODEL_NAME "Dumpsters_v1_garbadge"
#define DUMP_CONTAINER_MODEL_OBJECTPATH "WorldObject/Outside"
#define DUMP_CONTAINER_MODEL_TEXPATH "Outside/Container"
#define DUMP_CONTAINER_MODEL_EXTENTS XMFLOAT3(2.5f, 1.0f, 0.9f)
#define DUMP_CONTAINER_MODEL_TYPE Object_World
#define DUMP_CONTAINER_MODEL_COLLIDERTYPE Collider_Box
#define DUMP_CONTAINER_MODEL_MASS 9999
#define DUMP_CONTAINER_MODEL_SCALE XMFLOAT3(10,10,10)
#define DUMP_CONTAINER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define DUMP_CONTAINER_MODEL_SHADOW true

#define OUTSIDE_WOOD_CHAIR_MODEL_NAME "chair"
#define OUTSIDE_WOOD_CHAIR_MODEL_OBJECTPATH "WorldObject/Outside"
#define OUTSIDE_WOOD_CHAIR_MODEL_TEXPATH "Outside/Planks"
#define OUTSIDE_WOOD_CHAIR_MODEL_EXTENTS XMFLOAT3(0.25f, 0.2f, 0.3f)
#define OUTSIDE_WOOD_CHAIR_MODEL_TYPE Object_Movable
#define OUTSIDE_WOOD_CHAIR_MODEL_COLLIDERTYPE Collider_Box
#define OUTSIDE_WOOD_CHAIR_MODEL_MASS 10
#define OUTSIDE_WOOD_CHAIR_MODEL_SCALE XMFLOAT3(10,10,10)
#define OUTSIDE_WOOD_CHAIR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define OUTSIDE_WOOD_CHAIR_MODEL_SHADOW true

#define CONCRETE_FENCE1_MODEL_NAME "Concrete_fence_v1_column"
#define CONCRETE_FENCE1_MODEL_OBJECTPATH "WorldObject/Outside"
#define CONCRETE_FENCE1_MODEL_TEXPATH "Outside/Concrete_fence"
#define CONCRETE_FENCE1_MODEL_EXTENTS XMFLOAT3(0.35f, 1.7f, 0.35f)
#define CONCRETE_FENCE1_MODEL_TYPE Object_World
#define CONCRETE_FENCE1_MODEL_COLLIDERTYPE Collider_Box
#define CONCRETE_FENCE1_MODEL_MASS 9999
#define CONCRETE_FENCE1_MODEL_SCALE XMFLOAT3(10,10,10)
#define CONCRETE_FENCE1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CONCRETE_FENCE1_MODEL_SHADOW true

#define CONCRETE_FENCE2_MODEL_NAME "Concrete_fence_v1_wall_set_v1"
#define CONCRETE_FENCE2_MODEL_OBJECTPATH "WorldObject/Outside"
#define CONCRETE_FENCE2_MODEL_TEXPATH "Outside/Concrete_fence"
#define CONCRETE_FENCE2_MODEL_EXTENTS XMFLOAT3(0.4f, 1.6f, 4.5f)
#define CONCRETE_FENCE2_MODEL_TYPE Object_World
#define CONCRETE_FENCE2_MODEL_COLLIDERTYPE Collider_Box
#define CONCRETE_FENCE2_MODEL_MASS 9999
#define CONCRETE_FENCE2_MODEL_SCALE XMFLOAT3(10,10,10)
#define CONCRETE_FENCE2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CONCRETE_FENCE2_MODEL_SHADOW true

#define CONCRETE_FENCE3_MODEL_NAME "Concrete_fence_v1_wall_set_v2"
#define CONCRETE_FENCE3_MODEL_OBJECTPATH "WorldObject/Outside"
#define CONCRETE_FENCE3_MODEL_TEXPATH "Outside/Concrete_fence"
#define CONCRETE_FENCE3_MODEL_EXTENTS XMFLOAT3(0.4f, 1.6f, 9.4f)
#define CONCRETE_FENCE3_MODEL_TYPE Object_World
#define CONCRETE_FENCE3_MODEL_COLLIDERTYPE Collider_Box
#define CONCRETE_FENCE3_MODEL_MASS 9999
#define CONCRETE_FENCE3_MODEL_SCALE XMFLOAT3(10,10,10)
#define CONCRETE_FENCE3_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define CONCRETE_FENCE3_MODEL_SHADOW true

#define ELECTO_PANEL_MODEL_NAME "ElectoPanel"
#define ELECTO_PANEL_MODEL_OBJECTPATH "WorldObject/Outside"
#define ELECTO_PANEL_MODEL_TEXPATH "Outside/ElectricalPanel"
#define ELECTO_PANEL_MODEL_EXTENTS XMFLOAT3(0.14f, 0.22f, 1.3f)
#define ELECTO_PANEL_MODEL_TYPE Object_World
#define ELECTO_PANEL_MODEL_COLLIDERTYPE Collider_Box
#define ELECTO_PANEL_MODEL_MASS 9999
#define ELECTO_PANEL_MODEL_SCALE XMFLOAT3(10,10,10)
#define ELECTO_PANEL_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define ELECTO_PANEL_MODEL_SHADOW true

#define METAL_FENCE_MODEL_NAME "fence_segment_1"
#define METAL_FENCE_MODEL_OBJECTPATH "WorldObject/Outside"
#define METAL_FENCE_MODEL_TEXPATH "Outside/Fence"
#define METAL_FENCE_MODEL_EXTENTS XMFLOAT3(0.06f, 1.45f, 1.2f)
#define METAL_FENCE_MODEL_TYPE Object_World
#define METAL_FENCE_MODEL_COLLIDERTYPE Collider_Box
#define METAL_FENCE_MODEL_MASS 9999
#define METAL_FENCE_MODEL_SCALE XMFLOAT3(10,10,10)
#define METAL_FENCE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define METAL_FENCE_MODEL_SHADOW true

#define FLOOR_PANEL2_MODEL_NAME "floor-panel2"
#define FLOOR_PANEL2_MODEL_OBJECTPATH "WorldObject/Outside"
#define FLOOR_PANEL2_MODEL_TEXPATH "Outside/cor1_low_floor"
#define FLOOR_PANEL2_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define FLOOR_PANEL2_MODEL_TYPE Object_World
#define FLOOR_PANEL2_MODEL_COLLIDERTYPE Collider_None
#define FLOOR_PANEL2_MODEL_MASS 9999
#define FLOOR_PANEL2_MODEL_SCALE XMFLOAT3(10,10,10)
#define FLOOR_PANEL2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define FLOOR_PANEL2_MODEL_SHADOW true

#define HANGAR_MODEL_NAME "Hangar_v1_full"
#define HANGAR_MODEL_OBJECTPATH "WorldObject/Outside"
#define HANGAR_MODEL_TEXPATH "Outside/Hangar"
#define HANGAR_MODEL_EXTENTS XMFLOAT3(4.8f, 2.35f, 3.7f)
#define HANGAR_MODEL_TYPE Object_World
#define HANGAR_MODEL_COLLIDERTYPE Collider_Box
#define HANGAR_MODEL_MASS 9999
#define HANGAR_MODEL_SCALE XMFLOAT3(10,10,10)
#define HANGAR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define HANGAR_MODEL_SHADOW true

#define MACHINE1_MODEL_NAME "Machine_1"
#define MACHINE1_MODEL_OBJECTPATH "WorldObject/Outside"
#define MACHINE1_MODEL_TEXPATH "Outside/Machine"
#define MACHINE1_MODEL_EXTENTS XMFLOAT3(1.65f, 0.64f, 1.1f)
#define MACHINE1_MODEL_TYPE Object_World
#define MACHINE1_MODEL_COLLIDERTYPE Collider_Box
#define MACHINE1_MODEL_MASS 9999
#define MACHINE1_MODEL_SCALE XMFLOAT3(10,10,10)
#define MACHINE1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MACHINE1_MODEL_SHADOW true

#define MACHINE2_MODEL_NAME "Machine_2"
#define MACHINE2_MODEL_OBJECTPATH "WorldObject/Outside"
#define MACHINE2_MODEL_TEXPATH "Outside/Machine"
#define MACHINE2_MODEL_EXTENTS XMFLOAT3(2.2f, 1.0f, 1.05f)
#define MACHINE2_MODEL_TYPE Object_World
#define MACHINE2_MODEL_COLLIDERTYPE Collider_Box
#define MACHINE2_MODEL_MASS 9999
#define MACHINE2_MODEL_SCALE XMFLOAT3(10,10,10)
#define MACHINE2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MACHINE2_MODEL_SHADOW true

#define MACHINE3_MODEL_NAME "Machine_3"
#define MACHINE3_MODEL_OBJECTPATH "WorldObject/Outside"
#define MACHINE3_MODEL_TEXPATH "Outside/Machine"
#define MACHINE3_MODEL_EXTENTS XMFLOAT3(2.5f, 1.05f, 1.6f)
#define MACHINE3_MODEL_TYPE Object_World
#define MACHINE3_MODEL_COLLIDERTYPE Collider_Box
#define MACHINE3_MODEL_MASS 9999
#define MACHINE3_MODEL_SCALE XMFLOAT3(10,10,10)
#define MACHINE3_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MACHINE3_MODEL_SHADOW true

#define MACHINE6_MODEL_NAME "Machine_6"
#define MACHINE6_MODEL_OBJECTPATH "WorldObject/Outside"
#define MACHINE6_MODEL_TEXPATH "Outside/Machine"
#define MACHINE6_MODEL_EXTENTS XMFLOAT3(1.75f, 1.05f, 1.9f)
#define MACHINE6_MODEL_TYPE Object_World
#define MACHINE6_MODEL_COLLIDERTYPE Collider_Box
#define MACHINE6_MODEL_MASS 9999
#define MACHINE6_MODEL_SCALE XMFLOAT3(10,10,10)
#define MACHINE6_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MACHINE6_MODEL_SHADOW true

#define MACHINE7_MODEL_NAME "Machine_7"
#define MACHINE7_MODEL_OBJECTPATH "WorldObject/Outside"
#define MACHINE7_MODEL_TEXPATH "Outside/Machine"
#define MACHINE7_MODEL_EXTENTS XMFLOAT3(1.25f, 1.25f, 0.05f)
#define MACHINE7_MODEL_TYPE Object_World
#define MACHINE7_MODEL_COLLIDERTYPE Collider_Box
#define MACHINE7_MODEL_MASS 9999
#define MACHINE7_MODEL_SCALE XMFLOAT3(10,10,10)
#define MACHINE7_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define MACHINE7_MODEL_SHADOW true

#define OIL_TANK_MODEL_NAME "Oil_tank_v1"
#define OIL_TANK_MODEL_OBJECTPATH "WorldObject/Outside"
#define OIL_TANK_MODEL_TEXPATH "Outside/Oil_tank"
#define OIL_TANK_MODEL_EXTENTS XMFLOAT3(5.0f, 3.25f, 5.0f)
#define OIL_TANK_MODEL_TYPE Object_World
#define OIL_TANK_MODEL_COLLIDERTYPE Collider_Box
#define OIL_TANK_MODEL_MASS 9999
#define OIL_TANK_MODEL_SCALE XMFLOAT3(10,10,10)
#define OIL_TANK_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define OIL_TANK_MODEL_SHADOW true

#define OLD_SEA_TREE_MODEL_NAME "Old_Sea_Port_Tree"
#define OLD_SEA_TREE_MODEL_OBJECTPATH "WorldObject/Outside"
#define OLD_SEA_TREE_MODEL_TEXPATH "Outside/Tree"
#define OLD_SEA_TREE_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define OLD_SEA_TREE_MODEL_TYPE Object_World
#define OLD_SEA_TREE_MODEL_COLLIDERTYPE Collider_None
#define OLD_SEA_TREE_MODEL_MASS 9999
#define OLD_SEA_TREE_MODEL_SCALE XMFLOAT3(10,10,10)
#define OLD_SEA_TREE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define OLD_SEA_TREE_MODEL_SHADOW true

#define PIPE_MODEL_NAME "Pipe"
#define PIPE_MODEL_OBJECTPATH "WorldObject/Outside"
#define PIPE_MODEL_TEXPATH "Outside/Pipe"
#define PIPE_MODEL_EXTENTS XMFLOAT3(0.1f, 3.6f, 0.1f)
#define PIPE_MODEL_TYPE Object_World
#define PIPE_MODEL_COLLIDERTYPE Collider_Box
#define PIPE_MODEL_MASS 9999
#define PIPE_MODEL_SCALE XMFLOAT3(10,10,10)
#define PIPE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define PIPE_MODEL_SHADOW true

#define PIPE_PILE1_MODEL_NAME "Pipepile"
#define PIPE_PILE1_MODEL_OBJECTPATH "WorldObject/Outside"
#define PIPE_PILE1_MODEL_TEXPATH "Outside/Pipe"
#define PIPE_PILE1_MODEL_EXTENTS XMFLOAT3(1.65f, 0.6f, 0.9f)
#define PIPE_PILE1_MODEL_TYPE Object_World
#define PIPE_PILE1_MODEL_COLLIDERTYPE Collider_Box
#define PIPE_PILE1_MODEL_MASS 9999
#define PIPE_PILE1_MODEL_SCALE XMFLOAT3(10,10,10)
#define PIPE_PILE1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define PIPE_PILE1_MODEL_SHADOW true

#define PIPE_PILE2_MODEL_NAME "Pipepile1"
#define PIPE_PILE2_MODEL_OBJECTPATH "WorldObject/Outside"
#define PIPE_PILE2_MODEL_TEXPATH "Outside/Pipe"
#define PIPE_PILE2_MODEL_EXTENTS XMFLOAT3(1.65f, 0.27f, 0.55f)
#define PIPE_PILE2_MODEL_TYPE Object_World
#define PIPE_PILE2_MODEL_COLLIDERTYPE Collider_Box
#define PIPE_PILE2_MODEL_MASS 9999
#define PIPE_PILE2_MODEL_SCALE XMFLOAT3(10,10,10)
#define PIPE_PILE2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define PIPE_PILE2_MODEL_SHADOW true

#define ROAD_BLOCK_MODEL_NAME "Road_block_v1"
#define ROAD_BLOCK_MODEL_OBJECTPATH "WorldObject/Outside"
#define ROAD_BLOCK_MODEL_TEXPATH "Outside/Road_Block"
#define ROAD_BLOCK_MODEL_EXTENTS XMFLOAT3(1.15f, 0.55f, 0.5f)
#define ROAD_BLOCK_MODEL_TYPE Object_World
#define ROAD_BLOCK_MODEL_COLLIDERTYPE Collider_Box
#define ROAD_BLOCK_MODEL_MASS 9999
#define ROAD_BLOCK_MODEL_SCALE XMFLOAT3(10,10,10)
#define ROAD_BLOCK_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define ROAD_BLOCK_MODEL_SHADOW true

#define ROAD_B_FLOOR_MODEL_NAME "Road_set_v1_b_floor"
#define ROAD_B_FLOOR_MODEL_OBJECTPATH "WorldObject/Outside"
#define ROAD_B_FLOOR_MODEL_TEXPATH "Outside/Road"
#define ROAD_B_FLOOR_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define ROAD_B_FLOOR_MODEL_TYPE Object_World
#define ROAD_B_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define ROAD_B_FLOOR_MODEL_MASS 9999
#define ROAD_B_FLOOR_MODEL_SCALE XMFLOAT3(10,10,10)
#define ROAD_B_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define ROAD_B_FLOOR_MODEL_SHADOW false

#define ROAD_S_BEND2_MODEL_NAME "Road_set_v1_s_bend_2"
#define ROAD_S_BEND2_MODEL_OBJECTPATH "WorldObject/Outside"
#define ROAD_S_BEND2_MODEL_TEXPATH "Outside/Road"
#define ROAD_S_BEND2_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define ROAD_S_BEND2_MODEL_TYPE Object_World
#define ROAD_S_BEND2_MODEL_COLLIDERTYPE Collider_None
#define ROAD_S_BEND2_MODEL_MASS 9999
#define ROAD_S_BEND2_MODEL_SCALE XMFLOAT3(10,10,10)
#define ROAD_S_BEND2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define ROAD_S_BEND2_MODEL_SHADOW false

#define ROAD_S_FLOOR_MODEL_NAME "Road_set_v1_s_floor"
#define ROAD_S_FLOOR_MODEL_OBJECTPATH "WorldObject/Outside"
#define ROAD_S_FLOOR_MODEL_TEXPATH "Outside/Road"
#define ROAD_S_FLOOR_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define ROAD_S_FLOOR_MODEL_TYPE Object_World
#define ROAD_S_FLOOR_MODEL_COLLIDERTYPE Collider_None
#define ROAD_S_FLOOR_MODEL_MASS 9999
#define ROAD_S_FLOOR_MODEL_SCALE XMFLOAT3(10,10,10)
#define ROAD_S_FLOOR_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define ROAD_S_FLOOR_MODEL_SHADOW false

#define ROAD_S_TILE_MODEL_NAME "Road_set_v1_s_tile_2"
#define ROAD_S_TILE_MODEL_OBJECTPATH "WorldObject/Outside"
#define ROAD_S_TILE_MODEL_TEXPATH "Outside/Road"
#define ROAD_S_TILE_MODEL_EXTENTS XMFLOAT3(0.0f,0.0f,0.0f)
#define ROAD_S_TILE_MODEL_TYPE Object_World
#define ROAD_S_TILE_MODEL_COLLIDERTYPE Collider_None
#define ROAD_S_TILE_MODEL_MASS 9999
#define ROAD_S_TILE_MODEL_SCALE XMFLOAT3(10,10,10)
#define ROAD_S_TILE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define ROAD_S_TILE_MODEL_SHADOW false

#define SMALL_METALIC_CASE_MODEL_NAME "SmallMetalicCase"
#define SMALL_METALIC_CASE_MODEL_OBJECTPATH "WorldObject/Outside"
#define SMALL_METALIC_CASE_MODEL_TEXPATH "Outside/SmallMetalicCase"
#define SMALL_METALIC_CASE_MODEL_EXTENTS XMFLOAT3(0.425f, 0.34f, 0.3f)
#define SMALL_METALIC_CASE_MODEL_TYPE Object_Movable
#define SMALL_METALIC_CASE_MODEL_COLLIDERTYPE Collider_Box
#define SMALL_METALIC_CASE_MODEL_MASS 20
#define SMALL_METALIC_CASE_MODEL_SCALE XMFLOAT3(10,10,10)
#define SMALL_METALIC_CASE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define SMALL_METALIC_CASE_MODEL_SHADOW true

#define TOWER_MODEL_NAME "tower"
#define TOWER_MODEL_OBJECTPATH "WorldObject/Outside"
#define TOWER_MODEL_TEXPATH "Outside/Brick_Wall"
#define TOWER_MODEL_EXTENTS XMFLOAT3(3.0f, 3.0f, 4.0f)
#define TOWER_MODEL_TYPE Object_World
#define TOWER_MODEL_COLLIDERTYPE Collider_Box
#define TOWER_MODEL_MASS 9999
#define TOWER_MODEL_SCALE XMFLOAT3(10,10,10)
#define TOWER_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define TOWER_MODEL_SHADOW true

#define TOWER_SHORT_MODEL_NAME "tower_short"
#define TOWER_SHORT_MODEL_OBJECTPATH "WorldObject/Outside"
#define TOWER_SHORT_MODEL_TEXPATH "Outside/Brick_Wall"
#define TOWER_SHORT_MODEL_EXTENTS XMFLOAT3(3.0f, 3.0f, 4.0f)
#define TOWER_SHORT_MODEL_TYPE Object_World
#define TOWER_SHORT_MODEL_COLLIDERTYPE Collider_Box
#define TOWER_SHORT_MODEL_MASS 9999
#define TOWER_SHORT_MODEL_SCALE XMFLOAT3(10,10,10)
#define TOWER_SHORT_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define TOWER_SHORT_MODEL_SHADOW true

#define WOODEN_BOX_MODEL_NAME "Wooden_box_v1_LD1"
#define WOODEN_BOX_MODEL_OBJECTPATH "WorldObject/Outside"
#define WOODEN_BOX_MODEL_TEXPATH "Outside/Box"
#define WOODEN_BOX_MODEL_EXTENTS XMFLOAT3(0.55f, 0.34f, 0.95f)
#define WOODEN_BOX_MODEL_TYPE Object_Movable
#define WOODEN_BOX_MODEL_COLLIDERTYPE Collider_Box
#define WOODEN_BOX_MODEL_MASS 5
#define WOODEN_BOX_MODEL_SCALE XMFLOAT3(10,10,10)
#define WOODEN_BOX_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WOODEN_BOX_MODEL_SHADOW true

#define WOODEN_BOX_SQUARE_MODEL_NAME "Wooden_box_v1_LD1square"
#define WOODEN_BOX_SQUARE_MODEL_OBJECTPATH "WorldObject/Outside"
#define WOODEN_BOX_SQUARE_MODEL_TEXPATH "Outside/Box"
#define WOODEN_BOX_SQUARE_MODEL_EXTENTS XMFLOAT3(0.4f, 0.4f, 0.4f)
#define WOODEN_BOX_SQUARE_MODEL_TYPE Object_Movable
#define WOODEN_BOX_SQUARE_MODEL_COLLIDERTYPE Collider_Box
#define WOODEN_BOX_SQUARE_MODEL_MASS 5
#define WOODEN_BOX_SQUARE_MODEL_SCALE XMFLOAT3(10,10,10)
#define WOODEN_BOX_SQUARE_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh
#define WOODEN_BOX_SQUARE_MODEL_SHADOW true

#endif