#ifndef PROJECTILEDATA_H

#define PROJECTILEDATA_H

#include "../Common/Header/D3DUtil.h"
#include "../Common/Header/Struct.h"
#include "../DirectXRendering/Header/Global.h"

using namespace DirectX;

// Åõ»çÃ¼ ¸ðµ¨

#define PLAYER_PROJECTILE1_MODEL_NAME "Stone_1"
#define PLAYER_PROJECTILE1_MODEL_OBJECTPATH "PlayerProjectile"
#define PLAYER_PROJECTILE1_MODEL_TEXPATH "Projectile/Player_Stone"
#define PLAYER_PROJECTILE1_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define PLAYER_PROJECTILE1_MODEL_TYPE Object_PlayerProjectile
#define PLAYER_PROJECTILE1_MODEL_COLLIDERTYPE Collider_None
#define PLAYER_PROJECTILE1_MODEL_MASS 10
#define PLAYER_PROJECTILE1_MODEL_SCALE XMFLOAT3(10,10,10)
#define PLAYER_PROJECTILE1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh;
#define PLAYER_PROJECTILE1_MODEL_SHADOW true

#define PLAYER_PROJECTILE2_MODEL_NAME "Stone_2"
#define PLAYER_PROJECTILE2_MODEL_OBJECTPATH "PlayerProjectile"
#define PLAYER_PROJECTILE2_MODEL_TEXPATH "Projectile/Player_Stone"
#define PLAYER_PROJECTILE2_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define PLAYER_PROJECTILE2_MODEL_TYPE Object_PlayerProjectile
#define PLAYER_PROJECTILE2_MODEL_COLLIDERTYPE Collider_None
#define PLAYER_PROJECTILE2_MODEL_MASS 10
#define PLAYER_PROJECTILE2_MODEL_SCALE XMFLOAT3(10,10,10)
#define PLAYER_PROJECTILE2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh;
#define PLAYER_PROJECTILE2_MODEL_SHADOW true

#define PLAYER_PROJECTILE3_MODEL_NAME "Stone_3"
#define PLAYER_PROJECTILE3_MODEL_OBJECTPATH "PlayerProjectile"
#define PLAYER_PROJECTILE3_MODEL_TEXPATH "Projectile/Player_Stone"
#define PLAYER_PROJECTILE3_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define PLAYER_PROJECTILE3_MODEL_TYPE Object_PlayerProjectile
#define PLAYER_PROJECTILE3_MODEL_COLLIDERTYPE Collider_None
#define PLAYER_PROJECTILE3_MODEL_MASS 10
#define PLAYER_PROJECTILE3_MODEL_SCALE XMFLOAT3(10,10,10)
#define PLAYER_PROJECTILE3_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh;
#define PLAYER_PROJECTILE3_MODEL_SHADOW true

#define ENEMY_BULLET_MODEL_NAME "Bullet"
#define ENEMY_BULLET_MODEL_OBJECTPATH "Enemy_Projectile"
#define ENEMY_BULLET_MODEL_TEXPATH "Projectile/Enemy_Projectile"
#define ENEMY_BULLET_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define ENEMY_BULLET_MODEL_TYPE Object_EnemyProjectile
#define ENEMY_BULLET_MODEL_COLLIDERTYPE Collider_None
#define ENEMY_BULLET_MODEL_MASS 10
#define ENEMY_BULLET_MODEL_SCALE XMFLOAT3(7,7,7)
#define ENEMY_BULLET_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh;
#define ENEMY_BULLET_MODEL_SHADOW true

#define ENEMY_MISSILE1_MODEL_NAME "missile"
#define ENEMY_MISSILE1_MODEL_OBJECTPATH "Enemy_Projectile"
#define ENEMY_MISSILE1_MODEL_TEXPATH "Projectile/Enemy_Projectile"
#define ENEMY_MISSILE1_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define ENEMY_MISSILE1_MODEL_TYPE Object_EnemyProjectile
#define ENEMY_MISSILE1_MODEL_COLLIDERTYPE Collider_None
#define ENEMY_MISSILE1_MODEL_MASS 10
#define ENEMY_MISSILE1_MODEL_SCALE XMFLOAT3(0.5f,0.5f,0.5f)
#define ENEMY_MISSILE1_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh;
#define ENEMY_MISSILE1_MODEL_SHADOW true

#define ENEMY_MISSILE2_MODEL_NAME "missile_green"
#define ENEMY_MISSILE2_MODEL_OBJECTPATH "Enemy_Projectile"
#define ENEMY_MISSILE2_MODEL_TEXPATH "Projectile/Enemy_Projectile"
#define ENEMY_MISSILE2_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define ENEMY_MISSILE2_MODEL_TYPE Object_EnemyProjectile
#define ENEMY_MISSILE2_MODEL_COLLIDERTYPE Collider_None
#define ENEMY_MISSILE2_MODEL_MASS 10
#define ENEMY_MISSILE2_MODEL_SCALE XMFLOAT3(0.5f,0.5f,0.5f)
#define ENEMY_MISSILE2_MODEL_RENDERLAYER RenderLayer::Render_TextureMesh;
#define ENEMY_MISSILE2_MODEL_SHADOW true

#define ENEMY_MAGIC1_MODEL_NAME "Magic_Projectile"
#define ENEMY_MAGIC1_MODEL_OBJECTPATH "Enemy_Projectile"
#define ENEMY_MAGIC1_MODEL_TEXPATH "Projectile/Enemy_Projectile"
#define ENEMY_MAGIC1_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define ENEMY_MAGIC1_MODEL_TYPE Object_EnemyProjectile
#define ENEMY_MAGIC1_MODEL_COLLIDERTYPE Collider_None
#define ENEMY_MAGIC1_MODEL_MASS 10
#define ENEMY_MAGIC1_MODEL_SCALE XMFLOAT3(2.5f,2.5f,2.5f)
#define ENEMY_MAGIC1_MODEL_RENDERLAYER RenderLayer::Render_Static;
#define ENEMY_MAGIC1_MODEL_SHADOW true

#define ENEMY_MAGIC2_MODEL_NAME "Magic_Projectile_Chase"
#define ENEMY_MAGIC2_MODEL_OBJECTPATH "Enemy_Projectile"
#define ENEMY_MAGIC2_MODEL_TEXPATH "Projectile/Enemy_Projectile"
#define ENEMY_MAGIC2_MODEL_EXTENTS XMFLOAT3(0.2f, 0.5f, 0.2f)
#define ENEMY_MAGIC2_MODEL_TYPE Object_EnemyProjectile
#define ENEMY_MAGIC2_MODEL_COLLIDERTYPE Collider_None
#define ENEMY_MAGIC2_MODEL_MASS 10
#define ENEMY_MAGIC2_MODEL_SCALE XMFLOAT3(2.5f,2.5f,2.5f)
#define ENEMY_MAGIC2_MODEL_RENDERLAYER RenderLayer::Render_Static;
#define ENEMY_MAGIC2_MODEL_SHADOW true

#endif